// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozxkwccebiczoccgsmsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96eGt3Y2NlYmljem9jY2dzbXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTUyNjUsImV4cCI6MjA2MjI5MTI2NX0.wmgaRTzo062BLTEtCNyUTtCThsItxqivORdJtJ5t4V0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);